### ISSUE TITLE
How to use quinn-workbench's "Deep Space" feature with physical network interfaces instead of the in-memory network?

### ISSUE THREAD

**Issue by Knight112357** [aochagavia/quinn-workbench#5]
Sorry to bother you. I am currently exploring Quinn Workbench and am particularly interested in using its "Deep Space" feature, which is typically used with the in-memory network. However, I would like to implement it using a physical network interface instead of the in-memory network for real-world testing.

Could someone provide guidance or examples on how to configure Quinn to utilize "Deep Space" with an actual physical network interface (e.g., ens33, eth0) instead of the in-memory network? I am looking for steps on how to adjust the configuration or any changes in the code that would allow Quinn to operate over a physical network while leveraging the Deep Space feature.

Thanks in advance for your help!

**Comment by aochagavia** [comment]
Hello there! Which aspects of the "deep space" feature are you interested in? There are many things that would no longer work once you start using the physical network interface (e.g. time warping, determinism, injecting failures, etc). For your use case it might make more sense to create a new application from scratch (check out the [quinn docs](https://docs.rs/crate/quinn/0.11.5)) and use a tool such as `netem` to inject failures.

**Comment by marcblanchet** [comment]
@Knight112357 You can look at my initial work (before workbench) where I forked Quinn and modified the http client and server for deep space. See quinn/examples/{client, server}.rs and quinn-proto/congestion/no_cc.rs in https://github.com/marcblanchet/quinn-space. This is what was used for full testbed testing with VMs. But it has not been updated, as we are using workbench. So you may want to update it and as @aochagavia wrote, create a new application using Quinn.
